; zm_ (Zombie Plague Special 4.5): no Quake sounds (clash with ZP), no backweapons
amx_settings_api.amxx
zombie_plague_special_45.amxx
zpsp_zombie_classes.amxx
zpsp_human_classes.amxx
zp_game_mode_assassin_vs_sniper.amxx
zp_game_mode_nightmare.amxx
zpsp_game_mode_remix.amxx
gp_grenadetrail.amxx
nostalgia_parachute.amxx
