#!/usr/bin/env bash
set -euo pipefail

HLDS_DIR="${HLDS_DIR:-/opt/hlds}"
STATE_DIR="${STATE_DIR:-/state}"
LOGS_DIR="${LOGS_DIR:-/logs}"
CONTENT_DIR="${CONTENT_DIR:-/content}"
RUN_AS="${RUN_AS:-hlds}"

CSTRIKE="$HLDS_DIR/cstrike"
AMXX="$CSTRIKE/addons/amxmodx"

SERVER_NAME="${SERVER_NAME:-CS 1.6 Nostalgia | Multi-Mod}"
SV_PASSWORD="${SV_PASSWORD:-}"
FASTDL_URL="${FASTDL_URL:-}"
START_MAP="${START_MAP:-de_dust2}"
MAXPLAYERS="${MAXPLAYERS:-32}"
ADMINS="${ADMINS:-}"
MODERATORS="${MODERATORS:-}"
ANTICHEAT_ENABLED="${ANTICHEAT_ENABLED:-0}"
REUNION_ENABLED="${REUNION_ENABLED:-0}"
REUNION_SALT="${REUNION_SALT:-}"

ADMIN_FLAGS="abcdefghijklmnopqrstu"
MODERATOR_FLAGS="bcfiju"

log() { echo "[entrypoint] $*"; }
warn() { echo "[entrypoint] WARN: $*" >&2; }
die() { echo "[entrypoint] ERROR: $*" >&2; exit 1; }

require_cfg_safe() {
  local name="$1" value="$2"
  [[ "$value" != *[\"\;$'\n']* ]] || die "$name must not contain quotes, semicolons or newlines"
}

validate_env() {
  [ -n "${RCON_PASSWORD:-}" ] || die "RCON_PASSWORD is required"
  local name
  for name in RCON_PASSWORD SV_PASSWORD SERVER_NAME FASTDL_URL; do
    require_cfg_safe "$name" "${!name:-}"
  done
  [[ "$START_MAP" =~ ^[A-Za-z0-9_.-]+$ ]] || die "START_MAP is not a valid map name"
  [[ "$MAXPLAYERS" =~ ^[0-9]+$ ]] || die "MAXPLAYERS must be a number"
  if [ -n "$FASTDL_URL" ]; then
    [[ "$FASTDL_URL" == http://* ]] || die "FASTDL_URL must be plain http:// (GoldSrc cannot download over https)"
    FASTDL_URL="${FASTDL_URL%/}/"
  fi
}

render_env_cfg() {
  cat > "$CSTRIKE/env.cfg" <<EOF
hostname "$SERVER_NAME"
rcon_password "$RCON_PASSWORD"
sv_password "$SV_PASSWORD"
sv_downloadurl "$FASTDL_URL"
EOF
}

render_motd() {
  if [ -n "$FASTDL_URL" ]; then
    echo "${FASTDL_URL}motd.html" > "$CSTRIKE/motd.txt"
  else
    echo "$SERVER_NAME - say rtv, nominate, /rs, /rank, /top15" > "$CSTRIKE/motd.txt"
  fi
}

append_users() {
  local ids="$1" flags="$2" id
  IFS=',' read -ra entries <<< "$ids"
  for id in "${entries[@]}"; do
    id="${id//[[:space:]]/}"
    [ -n "$id" ] || continue
    [[ "$id" =~ ^(STEAM|VALVE)_[0-5]:[01]:[0-9]+$ ]] || die "invalid SteamID '$id'"
    echo "\"$id\" \"\" \"$flags\" \"ce\""
  done
}

render_users_ini() {
  {
    echo "; generated by entrypoint.sh from ADMINS and MODERATORS"
    append_users "$ADMINS" "$ADMIN_FLAGS"
    append_users "$MODERATORS" "$MODERATOR_FLAGS"
  } > "$AMXX/configs/users.ini"
}

render_metamod_plugins() {
  local plugins="$CSTRIKE/addons/metamod/plugins.ini"
  echo "linux addons/amxmodx/dlls/amxmodx_mm_i386.so" > "$plugins"

  if [ "$REUNION_ENABLED" = "1" ]; then
    local reunion="$CSTRIKE/addons/reunion/reunion_mm_i386.so"
    [ -f "$reunion" ] || die "REUNION_ENABLED=1 but $reunion is missing (see server/plugins/MANIFEST.md)"
    [ "${#REUNION_SALT}" -ge 16 ] || die "REUNION_SALT must have at least 16 characters"
    [[ "$REUNION_SALT" =~ ^[A-Za-z0-9]+$ ]] || die "REUNION_SALT must be alphanumeric"
    [ -f "$CSTRIKE/reunion.cfg" ] || die "reunion.cfg is missing (ships with Reunion, see MANIFEST.md)"
    sed -i "s|^SteamIdHashSalt.*|SteamIdHashSalt = $REUNION_SALT|" "$CSTRIKE/reunion.cfg"
    echo "linux addons/reunion/reunion_mm_i386.so" >> "$plugins"
    log "Reunion enabled"
  fi

  if [ "$ANTICHEAT_ENABLED" = "1" ]; then
    local whb candidates=("$CSTRIKE"/addons/whblocker/*_mm_i386.so)
    whb="${candidates[0]}"
    if [ -f "$whb" ]; then
      echo "linux ${whb#"$CSTRIKE/"}" >> "$plugins"
      log "anti-cheat (WHBlocker) enabled"
    else
      warn "ANTICHEAT_ENABLED=1 but no addons/whblocker/*_mm_i386.so found; anti-cheat stays off"
    fi
  fi
}

link_path() {
  local target="$1" link="$2"
  if [ -e "$link" ] && [ ! -L "$link" ]; then
    rm -rf "$link"
  fi
  ln -sfn "$target" "$link"
}

link_state() {
  mkdir -p "$STATE_DIR/amxx/vault" "$LOGS_DIR/hlds" "$LOGS_DIR/amxx"
  touch "$STATE_DIR/banned.cfg" "$STATE_DIR/listip.cfg"
  link_path "$STATE_DIR/amxx/csstats.dat" "$AMXX/data/csstats.dat"
  link_path "$STATE_DIR/amxx/vault" "$AMXX/data/vault"
  link_path "$STATE_DIR/banned.cfg" "$CSTRIKE/banned.cfg"
  link_path "$STATE_DIR/listip.cfg" "$CSTRIKE/listip.cfg"
  link_path "$LOGS_DIR/hlds" "$CSTRIKE/logs"
  link_path "$LOGS_DIR/amxx" "$AMXX/logs"
}

link_content() {
  [ -d "$CONTENT_DIR" ] || { warn "$CONTENT_DIR not mounted; custom maps unavailable"; return; }
  find "$CSTRIKE" -xtype l -lname "$CONTENT_DIR/*" -delete
  cp -rsf "$CONTENT_DIR/." "$CSTRIKE/"
}

render_mapcycle() {
  local map available=()
  while read -r map; do
    map="${map%%//*}"
    map="${map//[[:space:]]/}"
    [ -n "$map" ] || continue
    if [ -e "$CSTRIKE/maps/$map.bsp" ]; then
      available+=("$map")
    else
      warn "map '$map' listed in mapcycle.all.txt but maps/$map.bsp is missing; skipped"
    fi
  done < "$CSTRIKE/mapcycle.all.txt"
  [ "${#available[@]}" -gt 0 ] || die "no map from mapcycle.all.txt is available"
  printf '%s\n' "${available[@]}" > "$CSTRIKE/mapcycle.txt"
  log "mapcycle: ${#available[@]} maps available"
}

check_plugins() {
  local ini list name
  for ini in "$AMXX/configs/plugins.ini" "$AMXX"/configs/maps/plugins-*.ini; do
    [ -f "$ini" ] || continue
    list="${ini##*/}"
    while read -r name _; do
      [[ -z "$name" || "$name" == \;* ]] && continue
      [ -f "$AMXX/plugins/$name" ] || warn "$list: $name not installed (see server/plugins/MANIFEST.md)"
    done < "$ini"
  done
}

main() {
  validate_env
  render_env_cfg
  render_motd
  render_users_ini
  render_metamod_plugins
  link_state
  link_content
  render_mapcycle
  check_plugins

  if [ "$(id -u)" = "0" ] && id "$RUN_AS" >/dev/null 2>&1; then
    chown -R "$RUN_AS:$RUN_AS" "$STATE_DIR" "$LOGS_DIR"
    chown -h "$RUN_AS:$RUN_AS" "$CSTRIKE/env.cfg" "$CSTRIKE/motd.txt" "$CSTRIKE/mapcycle.txt"
  fi

  if [ "$#" -eq 0 ]; then
    cd "$HLDS_DIR"
    set -- ./hlds_linux -game cstrike -console -port 27015 +ip 0.0.0.0 \
      +sv_lan 0 +maxplayers "$MAXPLAYERS" +sys_ticrate 1000 +map "$START_MAP"
  fi

  if [ "$(id -u)" = "0" ] && id "$RUN_AS" >/dev/null 2>&1; then
    HOME="$(getent passwd "$RUN_AS" | cut -d: -f6)"
    export HOME
    exec setpriv --reuid="$RUN_AS" --regid="$RUN_AS" --init-groups "$@"
  fi
  exec "$@"
}

main "$@"
